{% set name = "libipt" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/intel/libipt/archive/refs/tags/v{{ version }}.tar.gz

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x") }}

requirements:
  build:
    - cmake >=3.29
    - ninja >=1.11.1
    - {{ compiler('c') }}
    - {{ stdlib('c') }}

about:
  home: https://github.com/intel/libipt
  summary: 'Unified Tracing and Profiling Tool'
  description: |
    libipt - an Intel(R) Processor Trace decoder library
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://github.com/intel/libipt
  dev_url: https://github.com/intel/libipt

extra:
  recipe-maintainers:
    - ZzEeKkAa
    - oleksandr-pavlyk
