{% set name = "gdb-oneapi" %}
{% set version = "2024.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/intel/gdb/archive/refs/tags/oneapi-{{ version }}.tar.gz

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - make >=3.82
  host:
    - python
    - ncurses
    - texinfo
    - xz
    - zlib
    - readline
    - gmp
    - mpfr
    - binutils_linux-64
    - bison
    - yaml-cpp
    - intel-graphics-compiler
    - libipt
    - level-zero-devel >=1.16
  run:
    - python
    - {{ pin_compatible('ncurses', min_pin='x.x', max_pin='x') }}
    - {{ pin_compatible('xz', min_pin='x.x', max_pin='x') }}
    - {{ pin_compatible('zlib', min_pin='x.x', max_pin='x') }}
    - six
    - pygments
    - {{ pin_compatible('libipt', min_pin='x.x', max_pin='x') }}
    - {{ pin_compatible('level-zero', min_pin='x.x', max_pin='x') }}

about:
  home: https://github.com/intel/gdb
  license: GPL-3.0-only
  license_family: GPL
  license_file: gdb/COPYING
  summary: 'Intel(R) Distribution for GDB*'
  description: |
    GDB, the GNU Project debugger, allows you to see what is going on `inside'
    another program while it executes -- or what another program was doing at
    the moment it crashed.
    The program being debugged can be written in Ada, C, C++, Objective-C,
    Pascal (and many other languages). Those programs might be executing on the
    same machine as GDB (native) or on another machine (remote).
    GDB can run on most popular UNIX and Microsoft Windows variants.
  doc_url: https://github.com/intel/gdb
  dev_url: https://github.com/intel/gdb

extra:
  recipe-maintainers:
    - ZzEeKkAa
    - oleksandr-pavlyk
