{% set name = "spirv-headers" %}
{% set version = "1.3.283.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/KhronosGroup/SPIRV-Headers/archive/refs/tags/vulkan-sdk-{{ version }}.tar.gz
    # sha256: 32b4c6ae6a2fa9b56c2c17233c8056da47e331f76e117729925825ea3e77a739

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make    # [unix]
    - ninja   # [win]
  host:
  run:

test:
  commands:
    - test -f ${PREFIX}/include/spirv/1.2/spirv.h             # [unix]
    - if not exist %LIBRARY_INC%\\spirv\\1.2\\spirv.h exit 1  # [win]

about:
  home: https://github.com/KhronosGroup/SPIRV-Headers
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Machine-readable files for the SPIR-V Registry

extra:
  recipe-maintainers:
    - isuruf
