{% set name = "opencl-clang" %}
{% set version = "14.0.6" %}
{% set spirv_headers_version = "1.3.283.0" %}
{% set llvm_version = version %}

package:
  name: intel-opencl-clang
  version: {{ version }}

source:
  # Important changes are constantly migrated to ocl-open-140 branch, but never
  # released
  git_url: https://github.com/intel/{{ name }}
  git_rev: ocl-open-140

build:
  number: 2
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - llvmdev   {{ llvm_version }}
    - llvm      {{ llvm_version }}
    - clangdev  {{ llvm_version }}
    - libclang-cpp  {{ llvm_version }}
    - llvm-spirv   {{ llvm_version }}
    - libllvmspirv {{ llvm_version }}
    - spirv-headers {{ spirv_headers_version }}
  run:
    - {{ pin_compatible("llvm-spirv", exact=True) }}

test:
  commands:
    - test -f ${PREFIX}/lib/libopencl_clang${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/intel/opencl-clang
  license: NCSA
  license_file: LICENSE
  license_family: BSD
  summary: Common clang is a thin wrapper library around clang. Common clang has OpenCL-oriented API and is capable to compile OpenCL C kernels to SPIR-V modules.

extra:
  recipe-maintainers:
    - isuruf
