{% set name = "intel-graphics-compiler" %}
{% set version = "1.0.16695.4" %}
{% set spirv_headers_version = "1.3.283.0" %}
{% set spirv_tools_version = "2024.1" %}
{% set llvm_spirv_version = "14.0.6" %}
{% set llvm_version = "14.0.6" %}
{% set vc_intrinsics_version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/intel/intel-graphics-compiler/archive/igc-{{ version }}.tar.gz
    folder: igc
  # TODO: create patch that uses conda installed packages
  - url: https://github.com/intel/vc-intrinsics/archive/refs/tags/v{{ vc_intrinsics_version }}.tar.gz
    folder: vc-intrinsics
  - git_url: https://github.com/KhronosGroup/SPIRV-LLVM-Translator
    git_rev: llvm_release_140
    folder: llvm-project/llvm/projects/llvm-spirv
  - url: https://github.com/KhronosGroup/SPIRV-Tools/archive/refs/tags/v{{ spirv_tools_version }}.tar.gz
    folder: SPIRV-Tools
  - url: https://github.com/KhronosGroup/SPIRV-Headers/archive/refs/tags/vulkan-sdk-{{ spirv_headers_version }}.tar.gz
    folder: SPIRV-Headers

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - flex
    - bison
  host:
    - llvmdev   {{ llvm_version }}
    - llvm      {{ llvm_version }}
    - clangdev  {{ llvm_version }}
    - intel-opencl-clang {{ llvm_version }}
    - llvm-spirv {{ llvm_spirv_version }}
    - libllvmspirv {{ llvm_spirv_version }}
    - zlib
    - mako
    - lld
    # TODO: use packages instead of sources
    # - spirv-tools {{ spirv_tools_version }}
    # - spirv-headers {{ spirv_headers_version }}
    # - vc-intrinsics {{ vc_intrinsics_version }}
  run:
    - intel-opencl-clang {{ llvm_version }}
    - {{ pin_compatible("llvm-spirv", max_pin="x.x.x.x.x.x") }}

test:
  commands:
    - test -f ${PREFIX}/lib/libiga64${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/intel/intel-graphics-compiler
  license: MIT
  license_file: igc/LICENSE.md
  license_family: MIT
  summary: The Intel(R) Graphics Compiler for OpenCL(TM) is an llvm based compiler for OpenCL(TM) targeting Intel Gen graphics hardware architecture.

extra:
  recipe-maintainers:
    - isuruf
